<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\ProductReview44\Repository;

use Doctrine\Persistence\ManagerRegistry;
use Eccube\Repository\AbstractRepository;
use Plugin\ProductReview44\Entity\ProductReviewConfig;

/**
 * ProductReview Config.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @extends AbstractRepository<ProductReviewConfig>
 */
class ProductReviewConfigRepository extends AbstractRepository
{
    /**
     * ProductReviewConfigRepository constructor.
     */
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, ProductReviewConfig::class);
    }

    public function get(int $id = 1): ?ProductReviewConfig
    {
        $result = $this->find($id);

        return $result instanceof ProductReviewConfig ? $result : null;
    }
}
